In [ ]:
# Importing libraries
import pandas as pd
import numpy as np

In [ ]:
# Reading dataset
df = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/supplement.csv")

In [ ]:
df

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
df.info

<bound method DataFrame.info of               ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Dis

In [ ]:
df.describe()

Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [ ]:
import plotly.express as px


In [ ]:
pie = df["Store_Type"].value_counts()
store = pie.index
orders = pie.values
fig = px.pie(df,values=orders , names=store)
fig.show()

In [ ]:
pie2 = df["Location_Type"].value_counts()
location=pie.index
orders = pie.values
fig = px.pie(df,values=orders,names=store)
fig.show()

In [ ]:
pie3 = df["Discount"].value_counts()
location=pie.index
orders = pie.values
fig = px.pie(df,values=orders,names=store)
fig.show()

In [ ]:
pie4 = df["Holiday"].value_counts()
location=pie.index
orders = pie.values
fig = px.pie(df,values=orders,names=store)
fig.show()

In [ ]:
df["Discount"]= df["Discount"].map({"No": 0 ,"Yes" : 1})

In [ ]:
df

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
df["Store_Type"]=df["Store_Type"].map({"S1" : 1,"S2" : 2,"S3" : 3,"S4" : 4})

In [ ]:
df

ID  Store_id  Store_Type Location_Type Region_Code        Date  \
0       T1000001         1           1            L3          R1  2018-01-01   
1       T1000002       253           4            L2          R1  2018-01-01   
2       T1000003       252           3            L2          R1  2018-01-01   
3       T1000004       251           2            L3          R1  2018-01-01   
4       T1000005       250           2            L3          R4  2018-01-01   
...          ...       ...         ...           ...         ...         ...   
188335  T1188336       149           2            L3          R2  2019-05-31   
188336  T1188337       153           4            L2          R1  2019-05-31   
188337  T1188338       154           1            L3          R2  2019-05-31   
188338  T1188339       155           3            L1          R2  2019-05-31   
188339  T1188340       152           2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
df["Location_Type"]=df["Location_Type"].map({"L1" : 1,"L2" : 2,"L3" : 3,"L4" : 4,"L5" : 5})

In [ ]:
df

ID  Store_id  Store_Type  Location_Type Region_Code        Date  \
0       T1000001         1           1            NaN          R1  2018-01-01   
1       T1000002       253           4            NaN          R1  2018-01-01   
2       T1000003       252           3            NaN          R1  2018-01-01   
3       T1000004       251           2            NaN          R1  2018-01-01   
4       T1000005       250           2            NaN          R4  2018-01-01   
...          ...       ...         ...            ...         ...         ...   
188335  T1188336       149           2            NaN          R2  2019-05-31   
188336  T1188337       153           4            NaN          R1  2019-05-31   
188337  T1188338       154           1            NaN          R2  2019-05-31   
188338  T1188339       155           3            NaN          R2  2019-05-31   
188339  T1188340       152           2            NaN          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
df["Region_Code"]=df["Region_Code"].map({"R1" : 1,"R2" : 2,"R3" : 3,"R4" : 4})

In [ ]:
df

ID  Store_id  Store_Type  Location_Type  Region_Code  \
0       T1000001         1           1            NaN            1   
1       T1000002       253           4            NaN            1   
2       T1000003       252           3            NaN            1   
3       T1000004       251           2            NaN            1   
4       T1000005       250           2            NaN            4   
...          ...       ...         ...            ...          ...   
188335  T1188336       149           2            NaN            2   
188336  T1188337       153           4            NaN            1   
188337  T1188338       154           1            NaN            2   
188338  T1188339       155           3            NaN            2   
188339  T1188340       152           2            NaN            1   

              Date  Holiday  Discount  #Order     Sales  
0       2018-01-01        1         1       9   7011.84  
1       2018-01-01        1         1      60  51789.12  
2       2018-01-01        1         1      42  36868.20  
3       2018-01-01        1         1      23  19715.16  
4       2018-01-01        1         1      62  45614.52  
...            ...      ...       ...     ...       ...  
188335  2019-05-31        1         1      51  37272.00  
188336  2019-05-31        1         0      90  54572.64  
188337  2019-05-31        1         0      56  31624.56  
188338  2019-05-31        1         1      70  49162.41  
188339  2019-05-31        1         0      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
x = np.array(df[["Store_Type","Location_Type","Region_Code","Holiday","Discount"]])
y = np.array(df["#Order"])

In [ ]:
x

array([[ 1., nan,  1.,  1.,  1.],
       [ 4., nan,  1.,  1.,  1.],
       [ 3., nan,  1.,  1.,  1.],
       ...,
       [ 1., nan,  2.,  1.,  0.],
       [ 3., nan,  2.,  1.,  1.],
       [ 2., nan,  1.,  1.,  0.]])

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
len(x_train)

150672

In [ ]:
import lightgbm as lgb
model = lgb.LGBMRegressor()


In [ ]:
model.fit(x_train,y_train)

LGBMRegressor()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([52.65180215, 96.06061996, 66.97992703, ..., 54.39360405,
       54.39360405, 84.38199799])

In [ ]:
y_test

array([ 54, 111,  59, ...,  40,  69,  68])

In [ ]:
accuracy = model.score(x_test,y_test)
print(accuracy)

0.5809855107906258


In [ ]:
data = pd.DataFrame(data={"Predicted orders" : y_pred.flatten()})


In [ ]:
data

Predicted orders
0             52.651802
1             96.060620
2             66.979927
3             99.574687
4             54.393604
...                 ...
37663         66.979927
37664         48.337727
37665         54.393604
37666         54.393604
37667         84.381998

[37668 rows x 1 columns]